### ISSUE TITLE
Add back rav1e and SVT-AV1

### ISSUE THREAD

**Issue by EwoutH** [eclipseo/image-comparison-sources#1]
It looks like [rav1e](https://github.com/xiph/rav1e) and [SVT-AV1](https://github.com/AOMediaCodec/SVT-AV1) were removed in https://github.com/eclipseo/image-comparison-sources/commit/86ea6dac1212bc32eef6ed41b625f364755a90cb. Is there any chance they could be added back?

**Comment by eclipseo** [comment]
This is on my todo list, I need to recompile libavif with support for them.

**Comment by eclipseo** [comment]
The problem I am facing is that neither svt-av1 nor rav1e support rgb/yuv444 import, and they don't support lossless mode either, which limit the pertinence in including them in the comparison.

**Comment by eclipseo** [comment]
OK I've added Rav1e and Svt-av1 and refactored the metrics graphs.
