### ISSUE TITLE
image-comparison-web sources

### ISSUE THREAD

**Issue by y-guyon** [eclipseo/image-comparison-sources#2]
Hello eclipseo,

The WebP/WebP2 team would like to set up a page similar to https://eclipseo.github.io/image-comparison-web with up-to-date codec results every week. We thought it would be better to keep your version instead of starting a new one.
- Is there any roadmap for future improvements or maintenance? It is written “Last updated: December 2020”; is it already updated once a month on average? Is there any way to access older results? Are codec git hashes (or versions) displayed somewhere?
- Do you have any plan of releasing the source code publicly? Alternatively we could add wp2, avif etc. to xooyoozoo’s version.

Some bug reports if relevant:
- URL hash arguments do not work: if one goes to https://eclipseo.github.io/image-comparison-web/#citroen*1:2&png=s&png=s, it lands to the default Abandoned Factory. https://xooyoozoo.github.io/yolo-octo-bugfixes/#cologne-cathedral&webp=s&bpg=s does not have this issue.
- At some resolutions and scale, the left image “trembles” when the cursor is moved, and it appears to be blurrier than the right one, even when comparing Original and Original. See license plate of https://xooyoozoo.github.io/yolo-octo-bugfixes/#citroen*1:2&png=s&png=s.

Thanks,
Yannis

**Comment by eclipseo** [comment]
>     * Is there any roadmap for future improvements or maintenance? It is written “Last updated: December 2020”; is it already updated once a month on average? Is there any way to access older results? Are codec git hashes (or versions) displayed somewhere?

I do not plan any update soon. I only have a laptop and it takes me a lot of time to generate the artefacts. Last time I updated it was last year I think. 

I don't keep old versions because it already exceeds the maximum size allowed on Github pages. Also the previous versions included different codecs/encoders that I don't judge pertinent to include anymore (Kakadu JPEG2000 (not available for free anymore), JPEG XR, Daala).

The codec git hashes are available in the "Full methodology" link:

> Codecs
>
> Alliance for Open Media AVIF: https://github.com/AOMediaCodec/libavif. The version used is 0.8.4.
> AOM AV1: https://aomedia.googlesource.com/aom/ The version used is v2.0.0.
> AOM/Intel SVT-AV1: https://github.com/AOMediaCodec/SVT-AV1 The version used is v0.8.6.
> Xiph RAV1E: https://github.com/xiph/rav1e The version used is v0.4.0-alpha.
> Fabrice Bellard BPG: https://github.com/mirrorer/libbpg. The version used is 0.9.7.
> Mozilla JPEG: https://github.com/mozilla/mozjpeg. The version used is 4.0.0.
> JPEG XL: https://gitlab.com/wg1/jpeg-xl. The version used is 0.1.1.
> Google WebP: https://chromium.googlesource.com/webm/libwebp. The version used is 1.1.0.
> Google WebP2: https://chromium.googlesource.com/codecs/libwebp2/. The version used is built from GIT revision 3724e165a6df9260eb30b9a731a9f9594d3c5703.
>
> Metrics
>
> The VMAF (Video Multi-Method Assessment Fusion) metric, MSSIM, SSIM, CIEDE2000 and PNSR-HVS are computed using vmaf, provided by Netflix: https://github.com/Netflix/vmaf. The version used is 2.0.0. Each metric compares two Y4M files.
>  SSImulacra: https://github.com/cloudinary/ssimulacra The version used is built from GIT revision 375726b13f9dec2a01950e6710e7e9f488c52ea3.
> DSSIM: https://github.com/kornelski/dssim The version used is built from GIT revision 159d623a55fe8ba9b27e381e6b30657080617678.
> Butteraugli: https://github.com/google/butteraugli The version used is built from GIT revision 71b18b636b9c7d1ae0c1d3730b85b3c127eb4511.
>
> Tools
>
> ffmpeg is used for image formats conversion. The version used is ffmpeg 3.3.2.
> ImageMagick identify is used to determine the width and height of images. The version used is ImageMagick 6.9.11-27.
> Python 3 timeit is used to mesure computing times.
> Python 3 Pandas and Numpy are used to compute means.
> Python 3 Matplot is used to plot graphs.
>
 

> Do you have any plan of releasing the source code publicly? Alternatively we could add wp2, avif etc. to xooyoozoo’s version.

What source code is not available publicly? As far as I know everything is available in this repo.


> URL hash arguments do not work: if one goes to https://eclipseo.github.io/image-comparison-web/#citroen*1:2&png=s&png=s, it lands to the default Abandoned Factory. https://xooyoozoo.github.io/yolo-octo-bugfixes/#cologne-cathedral&webp=s&bpg=s does not have this issue.`

I haven't change the Javascript code code much and I am really not familiar with it, as it is not commented and I amnot a good programmer.

> At some resolutions and scale, the left image “trembles” when the cursor is moved, and it appears to be blurrier than the right one, even when comparing Original and Original. See license plate of https://xooyoozoo.github.io/yolo-octo-bugfixes/#citroen*1:2&png=s&png=s.

Same as above, I haven't coded that part. I can reproduce the issue on a Blink based browser but not with Firefox.

**Comment by y-guyon** [comment]
Thanks for your quick and detailed answer.

> The codec git hashes are available in the "Full methodology" link:

Sorry about that, I looked for that information in the wrong section.

> What source code is not available publicly? As far as I know everything is available in this repo.

I can access [image-comparison-sources](https://github.com/eclipseo/image-comparison-sources) but [image-comparison-web](https://github.com/eclipseo/image-comparison-web) gives 404. I opened an issue here (the former) because I did not find the latter repository. I tried downloading the [web page](https://eclipseo.github.io/image-comparison-web) directly but it does not pull everything (images, json etc.) and it might raise license concerns.

> Same as above, I haven't coded that part. I can reproduce the issue on a Blink based browser but not with Firefox.

For the record I used Chrome on a ChromeBook and I think it also happens with Chrome on a Mac.

**Comment by eclipseo** [comment]
> > What source code is not available publicly? As far as I know everything is available in this repo.
> 
> I can access [image-comparison-sources](https://github.com/eclipseo/image-comparison-sources) but [image-comparison-web](https://github.com/eclipseo/image-comparison-web) gives 404. I opened an issue here (the former) because I did not find the latter repository. I tried downloading the [web page](https://eclipseo.github.io/image-comparison-web) directly but it does not pull everything (images, json etc.) and it might raise license concerns.
> 

It's it in the Github pages repo:
https://github.com/eclipseo/eclipseo.github.io

I'm currently reworking the code to make the window location hash working.

**Comment by eclipseo** [comment]
> > URL hash arguments do not work: if one goes to https://eclipseo.github.io/image-comparison-web/#citroen*1:2&png=s&png=s, it lands to the default Abandoned Factory. https://xooyoozoo.github.io/yolo-octo-bugfixes/#cologne-cathedral&webp=s&bpg=s does not have this issue.`
> 
> 
> I haven't change the Javascript code code much and I am really not familiar with it, as it is not commented and I amnot a good programmer.

Now it's working.

> > At some resolutions and scale, the left image “trembles” when the cursor is moved, and it appears to be blurrier than the right one, even when comparing Original and Original. See license plate of https://xooyoozoo.github.io/yolo-octo-bugfixes/#citroen*1:2&png=s&png=s.
> 
> Same as above, I haven't coded that part. I can reproduce the issue on a Blink based browser but not with Firefox.

It seems to be a bug in Chrome when a div is resized with a background image. I haven't found a workaround yet.

**Comment by y-guyon** [comment]
> Now it's working.

Great, thank you!

> It seems to be a bug in Chrome when a div is resized with a background image. I haven't found a workaround yet.

I sent two [pull requests](https://github.com/eclipseo/eclipseo.github.io/pulls). I did not found the background image. I understood it uses a `<canvas>` to render both images.
